### ISSUE TITLE
Collectory edit button needs to be reinstated

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/collectory-hub#8] opened 2022-10-18 04:05 UTC
Raised by @timhicks-ala

**Comment by sughics** [comment] 2022-12-14 22:53
Example Link: https://collections-test.ala.org.au/public/showDataResource/dr344 
When logged in as a Admin user, the page should show a "Edit" Button

![Image](https://user-images.githubusercontent.com/105408469/207732706-cdb344da-04a8-4062-9ba9-7ee0aae9ebcf.png)

**Comment by sughics** [comment] 2022-12-14 22:56
Currently working as expected in test and prod instances,.

**Comment by peggynewman** [comment] 2022-12-15 02:21
not working for me in test or prod

**Comment by adam-collins** [comment] 2023-06-12 01:59
Is this still a problem?

**Comment by peggynewman** [comment] 2023-06-12 08:04
yes

**Comment by adam-collins** [comment] 2023-06-13 23:59
Managed to reproduce the issue.
1. Open the link https://collections-test.ala.org.au/public/showDataResource/dr344
2. Clear `ALA-Auth` and `JSESSIONID` cookies.
3. Reload the page
4. Click `Login` and login.
5. `Edit` is now visible.
6. Invalidate `JSESSIONID` (edit or delete)
7. Reload the page
8. The `Edit` button is not visible as the user is not logged in, but the header button still indicates that the user is logged in and prevents the user from logging out.

Thinking out loud:
- Alter the `Logout` button to delete the `ALA-Auth` cookie.
- For the pages marked as `authenticateOnlyIfLoggedInFilterPattern`, delete the `ALA-Auth` cookie if `JSESSIONID` is not present or not valid.
- Is the cause of the issue because `authenticateOnlyIfLoggedInFilterPattern` is not operating as expected?

**Comment by adam-collins** [comment] 2023-06-14 05:09
Issue is on hold until auth-test behaves in the same way as auth prod.

**Comment by adam-collins** [comment] 2023-06-19 00:24
Because the ALA-Auth-Test cookie is absent on collections-test, the login button confusion is resolved. Leaving as TODO as this may change.

**Comment by kylie-m** [comment] 2023-08-18 07:19
Confirmed working for me in both test and production

**Closed as completed** 2023-08-18 07:20 UTC
